- asset_meta_information:
    asset_name: "template_vierge"
    asset_version: "0.0.3.31"
    author: "BEN OTHMANE Zied"
    author_email: "ziedici@gmail.com"
    description: "Say if population is old"
    long_description: "long_description"
    long_description_content_type: "text/markdown"
    url: "https://github.com/pypa/sampleproject"
    keywords:
      - "SOME"
      - "MEANINGFULL"
      - "KEYWORDS"
    project_urls:
      - Bug Tracker: "https://github.com/pypa/sampleproject/issues"
    classifiers:
      - "Programming Language :: Python :: 3"
      - "License :: OSI Approved :: MIT License"
      - "Operating System :: OS Independent"
      - "Topic :: Software Development :: Build Tools"
      - "Development Status :: 3 - Alpha"
      - "Intended Audience :: Developers"
      - "Programming Language :: Python :: 3.7"
    python_required : ">=3.7"
    copyright : "2023, BEN OTHMANE Zied"

- asset_parameters:
    - age_part:
        old : 45

- asset_default_data:
    example_data : "/.data/emp.csv"